name: Deploy To Heroku
on:
  pull_request:
    branches:
      - release
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load config vars into .env
        env:
          CONFIG_VARS: ${{ secrets.CONFIG_VARS }}
        run: echo $CONFIG_VARS > .env
      - name: Setup heroku API
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "a.rafaysaleem@gmail.com"
          env_file: ".env"
          
